import html
import os
import smtplib
from datetime import datetime, timezone
from email.message import EmailMessage

from .base import ExportSkill


def build_html_newsletter(title: str, markdown: str) -> str:
    rows = []
    for line in markdown.splitlines():
        safe_line = html.escape(line)
        if safe_line.startswith("## "):
            rows.append(f"<h2 style='color:#0f172a'>{safe_line[3:]}</h2>")
        elif safe_line.startswith("- "):
            rows.append(f"<p style='margin:4px 0;color:#334155'>{safe_line[2:]}</p>")
        elif safe_line.startswith("# "):
            rows.append(f"<h1 style='color:#111827'>{safe_line[2:]}</h1>")
        elif safe_line.strip():
            rows.append(f"<p style='margin:6px 0;color:#1f2937'>{safe_line}</p>")

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = "\n".join(rows)
    return f"""
<html>
  <body style="font-family:Arial,sans-serif;background:#f8fafc;padding:24px;">
    <div style="max-width:760px;margin:auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;padding:24px;">
      <p style="font-size:13px;color:#64748b;">每日 AI 晨報 · {generated}</p>
      {body}
      <hr style="margin-top:24px;border:none;border-top:1px solid #e2e8f0"/>
      <p style="font-size:12px;color:#94a3b8;">Generated by AI Trends Telegram Bot</p>
    </div>
  </body>
</html>
"""


class MailSkill(ExportSkill):
    name = "mail"

    def enabled(self) -> bool:
        return all(
            os.getenv(k)
            for k in ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "MAIL_TO", "MAIL_FROM"]
        )

    def run(self, title: str, markdown: str) -> str:
        if not self.enabled():
            return "Mail：未設定 SMTP 相關環境變數，已略過"

        msg = EmailMessage()
        msg["Subject"] = title
        msg["From"] = os.environ["MAIL_FROM"]
        msg["To"] = os.environ["MAIL_TO"]
        msg.set_content(markdown)
        msg.add_alternative(build_html_newsletter(title, markdown), subtype="html")

        with smtplib.SMTP(os.environ["SMTP_HOST"], int(os.environ["SMTP_PORT"]), timeout=20) as server:
            server.starttls()
            server.login(os.environ["SMTP_USER"], os.environ["SMTP_PASSWORD"])
            server.send_message(msg)

        return f"Mail：已寄送到 {os.environ['MAIL_TO']}"
